#!/usr/bin/env python3
"""CumBurSum report generator — consensus-led markdown output.

Leads with cross-database consensus themes (signals that surface in
multiple pathway annotation sources). Then per-database rankings as
supporting detail.
"""
from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from cumbursum.burden_scorer import MECHANISMS, PathwayBurden, Variant
from cumbursum.consensus import ConsensusTheme, DatabaseHit
from cumbursum.null_distribution import BurdenSignificance

logger = logging.getLogger(__name__)

SIG_STRONG = 0.01
SIG_WEAK = 0.05


def _fmt_p(p: float) -> str:
    if p == 0:
        return "<1e-6"
    if p < 0.001:
        return f"{p:.1e}"
    return f"{p:.3f}"


def _flag(p_adj: float) -> str:
    if p_adj < SIG_STRONG:
        return "🚨"
    if p_adj < SIG_WEAK:
        return "⚠️"
    return ""


def generate_markdown(
    person_name: str,
    variants: List[Variant],
    reactome_burdens: Dict[str, PathwayBurden],
    reactome_sig: Dict[str, Dict[str, BurdenSignificance]],
    hallmark_burdens: Dict[str, PathwayBurden],
    hallmark_sig: Dict[str, Dict[str, BurdenSignificance]],
    themes: List[ConsensusTheme],
    n_perm: int,
    cascade_path: str,
    constraint_by_gene: Optional[Dict[str, Dict[str, float]]] = None,
    mechanisms=MECHANISMS,
    top_per_mechanism: int = 20,
    include_full_table: bool = True,
) -> str:
    constraint_by_gene = constraint_by_gene or {}
    lines: List[str] = []

    # --- Header ---
    lines.append(f"# Pathway Burden Report — {person_name}")
    lines.append("")
    lines.append(f"*Generated by CumBurSum v0.1 on {datetime.now().isoformat(timespec='seconds')}*")
    lines.append("")
    lines.append("## The question this report answers")
    lines.append("")
    lines.append("> When a person carries multiple heterozygous AR-LOF or LP variants across "
                 "different genes that all feed **the same biological pathway**, current clinical "
                 "genomics dismisses each as 'just a carrier' and reports **nothing actionable**. "
                 "But the pathway itself may be cumulatively haploinsufficient — producing disease.")
    lines.append("")
    lines.append("> CumBurSum tests **pathway-level burden** across two independent annotation "
                 "databases. Signals that surface in **both** databases ('consensus themes') "
                 "are the claim: convergent biological dysfunction that single-variant classifiers miss.")
    lines.append("")

    # --- Run summary ---
    consensus_themes = [t for t in themes if t.is_consensus]
    lines.append("## Run summary")
    lines.append("")
    lines.append(f"- **Source:** `{cascade_path}`")
    lines.append(f"- **Variants after filtering (MT, noise families, etc.):** {len(variants)}")
    lines.append(f"- **Reactome pathways tested (with hierarchy rollup):** {len(reactome_burdens)}")
    lines.append(f"- **MSigDB Hallmarks tested:** {len(hallmark_burdens)}")
    lines.append(f"- **Permutations per pathway:** {n_perm}")
    lines.append(f"- **Cross-database consensus themes (≥2 DBs, p<0.05):** **{len(consensus_themes)}**")
    lines.append(f"- **Single-DB elevated themes:** {len(themes) - len(consensus_themes)}")
    lines.append("")

    # --- Consensus themes (the headline) ---
    lines.append("## 🔗 Cross-database consensus themes")
    lines.append("")
    if not consensus_themes:
        lines.append("*No themes surfaced at p<0.05 in ≥2 databases. Either the variant set is too "
                     "sparse or the pathway signal is genuinely weak. Check single-DB elevated themes "
                     "below — often real signals live there at one-DB resolution.*")
        lines.append("")
    else:
        lines.append("Themes below are **cross-validated** — they surface as elevated in both "
                     "Reactome (reaction-level and parent rollup) AND MSigDB Hallmarks (curated "
                     "broad-theme gene sets). Two orthogonally-curated databases agreeing reduces "
                     "the chance of database-specific artifact.")
        lines.append("")
        for i, theme in enumerate(consensus_themes, start=1):
            by_db: Dict[str, List[DatabaseHit]] = defaultdict(list)
            for h in theme.supporting_hits:
                by_db[h.db_name].append(h)
            lines.append(f"### {i}. {theme.theme_name}")
            lines.append("")
            # Driver gene roster with constraint info, if available
            driver_strs = []
            for g in sorted(theme.driver_genes):
                ci = constraint_by_gene.get(g)
                if ci:
                    driver_strs.append(f"{g} (pLI={ci.get('lof_pLI', 0):.2f})")
                else:
                    driver_strs.append(g)
            lines.append(f"- **Driver genes ({len(theme.driver_genes)}):** " + ", ".join(driver_strs))
            lines.append(f"- **Convergence score (Σ max adj_score per driver):** {theme.convergence_score:.2f}")
            lines.append(f"- **Best p (any DB):** {_fmt_p(theme.best_p)}")
            lines.append(f"- **Databases agreeing:** {theme.n_dbs}")
            # pLI summary: are drivers high-constraint (dominant) or low (AR-tolerant)?
            plis = [constraint_by_gene.get(g, {}).get("lof_pLI", 0.0) for g in theme.driver_genes]
            if plis:
                n_hipli = sum(1 for p in plis if p >= 0.9)
                n_lopli = sum(1 for p in plis if p < 0.5)
                if n_lopli >= 2 and n_hipli == 0:
                    lines.append(f"- **Constraint pattern:** 🧬 AR-convergent — {n_lopli}/{len(plis)} "
                                 f"drivers have pLI<0.5 (heterozygous-tolerant per gnomAD, "
                                 f"individually dismissed as 'carrier')")
                elif n_hipli >= 2:
                    lines.append(f"- **Constraint pattern:** dominant-burden — {n_hipli}/{len(plis)} "
                                 f"drivers have pLI≥0.9 (classic haploinsufficient)")

            # --- Clinical vs pathway interpretation (the novel-contribution display) ---
            lines.append("")
            lines.append("**🔍 Standard clinical vs. pathway-level interpretation**")
            lines.append("")
            # Per-driver: pull its most-informative variant from the variant list
            variants_by_gene: Dict[str, List[Variant]] = defaultdict(list)
            for v in variants:
                if v.gene in theme.driver_genes:
                    variants_by_gene[v.gene].append(v)

            lines.append("| Driver | Variant | Per-variant call | gnomAD pLI | Std. clinical reading | Pathway contribution |")
            lines.append("|---|---|---|---|---|---|")
            clinical_reads: List[str] = []
            for g in sorted(theme.driver_genes):
                vs = sorted(variants_by_gene.get(g, []), key=lambda v: -v.adj_score)
                if not vs:
                    continue
                v = vs[0]
                ci = constraint_by_gene.get(g, {})
                pli = f"{ci.get('lof_pLI', 0.0):.2f}" if ci else "—"
                cls = v.classification or "(unscored)"
                # Heuristic "what would a clinical lab say" — based on classification
                if cls.upper().startswith("P") and "VUS" not in cls.upper():
                    std = "pathogenic; check zygosity + inheritance"
                elif "LP" in cls.upper():
                    std = "likely pathogenic; check zygosity + inheritance"
                elif "VUS" in cls.upper():
                    std = "VUS; no action"
                elif "LB" in cls.upper() or "BENIGN" in cls.upper():
                    std = "benign; no action"
                else:
                    std = "carrier-level / no action"
                clinical_reads.append(std)
                lines.append(f"| {g} | {v.hgvs} | {cls} | {pli} | {std} | +{v.adj_score:.2f} |")
            lines.append("")
            # The money line
            lines.append(f"- **Standard clinical report would summarize these {len(theme.driver_genes)} variants as:** "
                         f"*individual findings — not actionable as a group*")
            lines.append(f"- **CumBurSum pathway view:** {len(theme.driver_genes)} drivers converge on "
                         f"**{theme.theme_name}** with a combined burden of {theme.convergence_score:.2f}, "
                         f"cross-validated across {theme.n_dbs} independent databases "
                         f"(best p={_fmt_p(theme.best_p)}). Pathway-level haploinsufficiency is the "
                         f"parsimonious explanation — invisible to per-variant classification.")
            lines.append("")
            lines.append("")
            lines.append(f"| Database | Pathway | Hits/Size | Burden | z | p |")
            lines.append(f"|---|---|---|---|---|---|")
            for db_name in sorted(by_db.keys()):
                for h in sorted(by_db[db_name], key=lambda h: h.p_value)[:3]:
                    lines.append(
                        f"| {h.db_name} | {h.pathway_name} | {len(h.genes_hit)}/{h.pathway_size} "
                        f"| {h.burden:.2f} | {h.z:.2f} | {_fmt_p(h.p_value)} |"
                    )
            lines.append("")

    # --- Single-DB themes (interesting but less reinforced) ---
    single_themes = [t for t in themes if not t.is_consensus]
    if single_themes:
        lines.append("## Single-database elevated themes")
        lines.append("")
        lines.append("These surface as elevated in only one database — either a database-specific "
                     "pathway with no equivalent gene set in the other, or a real signal that "
                     "happened not to converge. Use with more caution.")
        lines.append("")
        lines.append("| DB | Theme | Driver genes | Best p |")
        lines.append("|---|---|---|---|")
        for t in single_themes[:20]:
            dbs = {h.db_name for h in t.supporting_hits}
            db_str = ", ".join(sorted(dbs))
            genes = ", ".join(sorted(t.driver_genes)[:6])
            if len(t.driver_genes) > 6:
                genes += f" (+{len(t.driver_genes) - 6})"
            lines.append(f"| {db_str} | {t.theme_name} | {genes} | {_fmt_p(t.best_p)} |")
        lines.append("")

    # --- Per-database rankings (supporting detail) ---
    for db_name, burdens, sig in (
        ("Reactome", reactome_burdens, reactome_sig),
        ("Hallmarks", hallmark_burdens, hallmark_sig),
    ):
        lines.append(f"## Supporting detail: {db_name} rankings")
        lines.append("")
        for mech_title, mech in (("total burden", "total"), ("DN burden", "dn"), ("LOF burden", "lof")):
            lines.append(f"### Top {db_name} pathways by {mech_title}")
            lines.append("")
            lines.append("| # | Pathway | Genes hit | Burden | z | p | p (BH) | Flag |")
            lines.append("|---|---|---|---|---|---|---|---|")
            ranked = sorted(sig.keys(), key=lambda pid: (sig[pid][mech].p_value, -sig[pid][mech].observed))
            for i, pid in enumerate(ranked[:top_per_mechanism], start=1):
                b = burdens[pid]
                s = sig[pid][mech]
                genes = ", ".join(sorted(b.genes_hit)[:4])
                if b.n_genes_hit > 4:
                    genes += f" (+{b.n_genes_hit - 4})"
                lines.append(
                    f"| {i} | {b.pathway_name} | {genes} ({b.n_genes_hit}/{b.pathway_size}) "
                    f"| {s.observed:.2f} | {s.z:.2f} | {_fmt_p(s.p_value)} "
                    f"| {_fmt_p(s.p_adj)} | {_flag(s.p_adj)} |"
                )
            lines.append("")

    # --- Variant inventory ---
    lines.append("## Variant inventory")
    lines.append("")
    lines.append("| Gene | pLI | mis_oe | Variant | Consequence | gnomAD freq | adj_score | adj_dn | adj_lof | adj_gof |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for v in sorted(variants, key=lambda v: v.adj_score, reverse=True):
        freq = f"{v.gnomad_freq:.2e}" if v.gnomad_freq > 0 else "—"
        ci = constraint_by_gene.get(v.gene, {})
        pli = f"{ci['lof_pLI']:.2f}" if "lof_pLI" in ci else "—"
        mis = f"{ci['mis_oe']:.2f}" if "mis_oe" in ci else "—"
        lines.append(
            f"| {v.gene} | {pli} | {mis} | {v.hgvs} | {v.consequence} | {freq} "
            f"| {v.adj_score:.2f} | {v.adj_dn:.2f} | {v.adj_lof:.2f} | {v.adj_gof:.2f} |"
        )
    lines.append("")

    # --- Interpretation notes ---
    lines.append("## Reading this report")
    lines.append("")
    lines.append("- **A consensus theme** means the same biological function (defined by the "
                 "variant-hit genes) rose to top-ranked status in **both** Reactome and Hallmarks — "
                 "two independently-curated databases. That's stronger evidence than a single-DB hit.")
    lines.append("- **p-values are empirical permutation** (within-individual: 'is this pathway "
                 "more loaded than a random pathway of the same size for THIS variant set?'). "
                 "Benjamini-Hochberg adjusts for multiple testing per-database, per-mechanism.")
    lines.append("- **BH correction is conservative** for curated variant lists (these lists are "
                 "by design enriched for real signal, so the 'many null tests' assumption behind "
                 "BH is violated). Raw p-values matter more than BH-adjusted for hypothesis-enriched "
                 "input. For whole-exome / whole-genome unbiased input, BH is the appropriate lens.")
    lines.append("- **Consequence-based scoring**: frameshifts, stop-gains, and canonical splice "
                 "variants get deterministic LOF burden = 1.0, because CASCADE only mechanism-scores "
                 "missense. Missense variants use CASCADE-scored DN/LOF/GOF when available, PRIORITY-"
                 "shimmed otherwise.")
    lines.append("- **MT-* genes, mucin (MUC*) family, olfactory receptors, HLA, KRTAP, and other "
                 "high-noise polymorphic families are filtered** to prevent tandem-repeat artifacts "
                 "from inflating pathway burden.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("🚨 **Embargo:** CumBurSum is pre-publication for the Marrakech conference paper "
                 "(Ejjami, Healthcare Revolution in AI, Sept 9-10 2026). Do not redistribute until "
                 "embargo lifts.")
    lines.append("")
    return "\n".join(lines)


def write_report(out_path: Path, **kwargs) -> Path:
    md = generate_markdown(**kwargs)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    logger.info("Wrote report: %s (%d chars)", out_path, len(md))
    return out_path
